/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: ..\studio\schema.json
export type Link = {
  _type: 'link'
  linkType?: 'href' | 'page' | 'post'
  href?: string
  page?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'page'
  }
  post?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'post'
  }
  openInNewTab?: boolean
}

export type CallToAction = {
  _type: 'callToAction'
  eyebrow?: string
  heading: string
  body?: BlockContentTextOnly
  button?: Button
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  theme?: 'light' | 'dark'
  contentAlignment?: 'textFirst' | 'imageFirst'
}

export type InfoSection = {
  _type: 'infoSection'
  heading?: string
  subheading?: string
  content?: BlockContent
}

export type BlockContentTextOnly = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
  listItem?: 'bullet' | 'number'
  markDefs?: Array<{
    href?: string
    _type: 'link'
    _key: string
  }>
  level?: number
  _type: 'block'
  _key: string
}>

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        linkType?: 'href' | 'page' | 'post'
        href?: string
        page?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'page'
        }
        post?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'post'
        }
        openInNewTab?: boolean
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }
  | {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
      _key: string
    }
>

export type Button = {
  _type: 'button'
  buttonText?: string
  link?: Link
}

export type Settings = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      linkType?: 'href' | 'page' | 'post'
      href?: string
      page?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'page'
      }
      post?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'post'
      }
      openInNewTab?: boolean
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  ogImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    metadataBase?: string
    _type: 'image'
  }
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  heading: string
  subheading?: string
  pageBuilder?: Array<
    | ({
        _key: string
      } & CallToAction)
    | ({
        _key: string
      } & InfoSection)
  >
}

export type Post = {
  _id: string
  _type: 'post'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  content?: BlockContent
  excerpt?: string
  coverImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  date?: string
  author?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'person'
  }
}

export type Person = {
  _id: string
  _type: 'person'
  _createdAt: string
  _updatedAt: string
  _rev: string
  firstName: string
  lastName: string
  picture: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type SanityAssistInstructionTask = {
  _type: 'sanity.assist.instructionTask'
  path?: string
  instructionKey?: string
  started?: string
  updated?: string
  info?: string
}

export type SanityAssistTaskStatus = {
  _type: 'sanity.assist.task.status'
  tasks?: Array<
    {
      _key: string
    } & SanityAssistInstructionTask
  >
}

export type SanityAssistSchemaTypeAnnotations = {
  _type: 'sanity.assist.schemaType.annotations'
  title?: string
  fields?: Array<
    {
      _key: string
    } & SanityAssistSchemaTypeField
  >
}

export type SanityAssistOutputType = {
  _type: 'sanity.assist.output.type'
  type?: string
}

export type SanityAssistOutputField = {
  _type: 'sanity.assist.output.field'
  path?: string
}

export type SanityAssistInstructionContext = {
  _type: 'sanity.assist.instruction.context'
  reference: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'assist.instruction.context'
  }
}

export type AssistInstructionContext = {
  _id: string
  _type: 'assist.instruction.context'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  context?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type SanityAssistInstructionUserInput = {
  _type: 'sanity.assist.instruction.userInput'
  message: string
  description?: string
}

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<
    | {
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }
    | ({
        _key: string
      } & SanityAssistInstructionFieldRef)
    | ({
        _key: string
      } & SanityAssistInstructionContext)
    | ({
        _key: string
      } & SanityAssistInstructionUserInput)
  >
  style?: 'normal'
  listItem?: never
  markDefs?: null
  level?: number
  _type: 'block'
  _key: string
}>

export type SanityAssistInstructionFieldRef = {
  _type: 'sanity.assist.instruction.fieldRef'
  path?: string
}

export type SanityAssistInstruction = {
  _type: 'sanity.assist.instruction'
  prompt?: SanityAssistInstructionPrompt
  icon?: string
  title?: string
  userId?: string
  createdById?: string
  output?: Array<
    | ({
        _key: string
      } & SanityAssistOutputField)
    | ({
        _key: string
      } & SanityAssistOutputType)
  >
}

export type SanityAssistSchemaTypeField = {
  _type: 'sanity.assist.schemaType.field'
  path?: string
  instructions?: Array<
    {
      _key: string
    } & SanityAssistInstruction
  >
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | Link
  | CallToAction
  | InfoSection
  | BlockContentTextOnly
  | BlockContent
  | Button
  | Settings
  | SanityImageCrop
  | SanityImageHotspot
  | Page
  | Post
  | Person
  | Slug
  | SanityAssistInstructionTask
  | SanityAssistTaskStatus
  | SanityAssistSchemaTypeAnnotations
  | SanityAssistOutputType
  | SanityAssistOutputField
  | SanityAssistInstructionContext
  | AssistInstructionContext
  | SanityAssistInstructionUserInput
  | SanityAssistInstructionPrompt
  | SanityAssistInstructionFieldRef
  | SanityAssistInstruction
  | SanityAssistSchemaTypeField
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: sanity\lib\queries.ts
// Variable: settingsQuery
// Query: *[_type == "settings"][0]
export type SettingsQueryResult = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      linkType?: 'href' | 'page' | 'post'
      href?: string
      page?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'page'
      }
      post?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'post'
      }
      openInNewTab?: boolean
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  ogImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    metadataBase?: string
    _type: 'image'
  }
} | null

// Source: sanity\lib\queries.ts
// Variable: storeSettingsQuery
// Query: *[_type == "storeSettings"][0]{  storeName,  tagline,  logo,  heroImage,  heroTitle,  heroSubtitle,  "featuredCategories": featuredCategories[]->{    _id,    name,    "slug": slug.current,    description,    image  },  aboutSection,  contactInfo,  socialMedia,  deliveryInfo,  announcement}
export type StoreSettingsQueryResult = null

// Source: sanity\lib\queries.ts
// Variable: allProductsQuery
// Query: *[_type == "product" && isAvailable == true] | order(isFeatured desc, name asc) {      _id,  name,  "slug": slug.current,  description,  image,  gallery,  "category": category->{    _id,    name,    "slug": slug.current  },  basePrice,  servingSize,  servesCount,  "addOns": addOns[]->{    _id,    name,    "slug": slug.current,    description,    price,    image,    isAvailable  },  "seasonings": seasonings[]->{    _id,    name,    "slug": slug.current,    description,    price,    image,    isIncludedByDefault,    isAvailable  },  ingredients,  nutritionInfo,  isAvailable,  isFeatured,  preparationTime  }
export type AllProductsQueryResult = Array<never>

// Source: sanity\lib\queries.ts
// Variable: featuredProductsQuery
// Query: *[_type == "product" && isAvailable == true && isFeatured == true] | order(name asc) {      _id,  name,  "slug": slug.current,  description,  image,  gallery,  "category": category->{    _id,    name,    "slug": slug.current  },  basePrice,  servingSize,  servesCount,  "addOns": addOns[]->{    _id,    name,    "slug": slug.current,    description,    price,    image,    isAvailable  },  "seasonings": seasonings[]->{    _id,    name,    "slug": slug.current,    description,    price,    image,    isIncludedByDefault,    isAvailable  },  ingredients,  nutritionInfo,  isAvailable,  isFeatured,  preparationTime  }
export type FeaturedProductsQueryResult = Array<never>

// Source: sanity\lib\queries.ts
// Variable: productBySlugQuery
// Query: *[_type == "product" && slug.current == $slug][0] {      _id,  name,  "slug": slug.current,  description,  image,  gallery,  "category": category->{    _id,    name,    "slug": slug.current  },  basePrice,  servingSize,  servesCount,  "addOns": addOns[]->{    _id,    name,    "slug": slug.current,    description,    price,    image,    isAvailable  },  "seasonings": seasonings[]->{    _id,    name,    "slug": slug.current,    description,    price,    image,    isIncludedByDefault,    isAvailable  },  ingredients,  nutritionInfo,  isAvailable,  isFeatured,  preparationTime  }
export type ProductBySlugQueryResult = null

// Source: sanity\lib\queries.ts
// Variable: productsByCategoryQuery
// Query: *[_type == "product" && isAvailable == true && category->slug.current == $categorySlug] | order(name asc) {      _id,  name,  "slug": slug.current,  description,  image,  gallery,  "category": category->{    _id,    name,    "slug": slug.current  },  basePrice,  servingSize,  servesCount,  "addOns": addOns[]->{    _id,    name,    "slug": slug.current,    description,    price,    image,    isAvailable  },  "seasonings": seasonings[]->{    _id,    name,    "slug": slug.current,    description,    price,    image,    isIncludedByDefault,    isAvailable  },  ingredients,  nutritionInfo,  isAvailable,  isFeatured,  preparationTime  }
export type ProductsByCategoryQueryResult = Array<never>

// Source: sanity\lib\queries.ts
// Variable: allCategoriesQuery
// Query: *[_type == "productCategory"] | order(order asc, name asc) {    _id,    name,    "slug": slug.current,    description,    image,    "productCount": count(*[_type == "product" && references(^._id) && isAvailable == true])  }
export type AllCategoriesQueryResult = Array<never>

// Source: sanity\lib\queries.ts
// Variable: categoryBySlugQuery
// Query: *[_type == "productCategory" && slug.current == $slug][0] {    _id,    name,    "slug": slug.current,    description,    image  }
export type CategoryBySlugQueryResult = null

// Source: sanity\lib\queries.ts
// Variable: allAddOnsQuery
// Query: *[_type == "productAddOn" && isAvailable == true] | order(name asc) {    _id,    name,    "slug": slug.current,    description,    price,    image  }
export type AllAddOnsQueryResult = Array<never>

// Source: sanity\lib\queries.ts
// Variable: allSeasoningsQuery
// Query: *[_type == "seasoning" && isAvailable == true] | order(name asc) {    _id,    name,    "slug": slug.current,    description,    price,    image,    isIncludedByDefault  }
export type AllSeasoningsQueryResult = Array<never>

// Source: sanity\lib\queries.ts
// Variable: getPageQuery
// Query: *[_type == 'page' && slug.current == $slug][0]{    _id,    _type,    name,    slug,    heading,    subheading,    "pageBuilder": pageBuilder[]{      ...,      _type == "callToAction" => {        ...,        button {          ...,            link {      ...,        _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  }      }        }      },      _type == "infoSection" => {        content[]{          ...,          markDefs[]{            ...,              _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  }          }        }      },    },  }
export type GetPageQueryResult = {
  _id: string
  _type: 'page'
  name: string
  slug: Slug
  heading: string
  subheading: string | null
  pageBuilder: Array<
    | {
        _key: string
        _type: 'callToAction'
        eyebrow?: string
        heading: string
        body?: BlockContentTextOnly
        button: {
          _type: 'button'
          buttonText?: string
          link: {
            _type: 'link'
            linkType?: 'href' | 'page' | 'post'
            href?: string
            page: string | null
            post: string | null
            openInNewTab?: boolean
          } | null
        } | null
        image?: {
          asset?: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
          }
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        }
        theme?: 'dark' | 'light'
        contentAlignment?: 'imageFirst' | 'textFirst'
      }
    | {
        _key: string
        _type: 'infoSection'
        heading?: string
        subheading?: string
        content: Array<
          | {
              children?: Array<{
                marks?: Array<string>
                text?: string
                _type: 'span'
                _key: string
              }>
              style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
              listItem?: 'bullet' | 'number'
              markDefs: Array<{
                linkType?: 'href' | 'page' | 'post'
                href?: string
                page: string | null
                post: string | null
                openInNewTab?: boolean
                _type: 'link'
                _key: string
              }> | null
              level?: number
              _type: 'block'
              _key: string
            }
          | {
              asset?: {
                _ref: string
                _type: 'reference'
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
              }
              media?: unknown
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              _type: 'image'
              _key: string
              markDefs: null
            }
        > | null
      }
  > | null
} | null

// Source: sanity\lib\queries.ts
// Variable: sitemapData
// Query: *[_type == "page" || _type == "post" && defined(slug.current)] | order(_type asc) {    "slug": slug.current,    _type,    _updatedAt,  }
export type SitemapDataResult = Array<
  | {
      slug: string
      _type: 'page'
      _updatedAt: string
    }
  | {
      slug: string
      _type: 'post'
      _updatedAt: string
    }
>

// Source: sanity\lib\queries.ts
// Variable: allPostsQuery
// Query: *[_type == "post" && defined(slug.current)] | order(date desc, _updatedAt desc) {      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  excerpt,  coverImage,  "date": coalesce(date, _updatedAt),  "author": author->{firstName, lastName, picture},  }
export type AllPostsQueryResult = Array<{
  _id: string
  status: 'draft' | 'published'
  title: string
  slug: string
  excerpt: string | null
  coverImage: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  } | null
  date: string
  author: {
    firstName: string
    lastName: string
    picture: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
  } | null
}>

// Source: sanity\lib\queries.ts
// Variable: morePostsQuery
// Query: *[_type == "post" && _id != $skip && defined(slug.current)] | order(date desc, _updatedAt desc) [0...$limit] {      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  excerpt,  coverImage,  "date": coalesce(date, _updatedAt),  "author": author->{firstName, lastName, picture},  }
export type MorePostsQueryResult = Array<{
  _id: string
  status: 'draft' | 'published'
  title: string
  slug: string
  excerpt: string | null
  coverImage: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  } | null
  date: string
  author: {
    firstName: string
    lastName: string
    picture: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
  } | null
}>

// Source: sanity\lib\queries.ts
// Variable: postQuery
// Query: *[_type == "post" && slug.current == $slug] [0] {    content[]{    ...,    markDefs[]{      ...,        _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  }    }  },      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  excerpt,  coverImage,  "date": coalesce(date, _updatedAt),  "author": author->{firstName, lastName, picture},  }
export type PostQueryResult = {
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
        listItem?: 'bullet' | 'number'
        markDefs: Array<{
          linkType?: 'href' | 'page' | 'post'
          href?: string
          page: string | null
          post: string | null
          openInNewTab?: boolean
          _type: 'link'
          _key: string
        }> | null
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
        markDefs: null
      }
  > | null
  _id: string
  status: 'draft' | 'published'
  title: string
  slug: string
  excerpt: string | null
  coverImage: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  } | null
  date: string
  author: {
    firstName: string
    lastName: string
    picture: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
  } | null
} | null

// Source: sanity\lib\queries.ts
// Variable: postPagesSlugs
// Query: *[_type == "post" && defined(slug.current)]  {"slug": slug.current}
export type PostPagesSlugsResult = Array<{
  slug: string
}>

// Source: sanity\lib\queries.ts
// Variable: pagesSlugs
// Query: *[_type == "page" && defined(slug.current)]  {"slug": slug.current}
export type PagesSlugsResult = Array<{
  slug: string
}>

// Source: sanity\lib\queries.ts
// Variable: aboutPageQuery
// Query: *[_type == "aboutPage"][0]{    title,    heroImage,    heroTitle,    heroSubtitle,    mainContent,    mission,    vision,    values,    teamSection,    ctaSection,    seo  }
export type AboutPageQueryResult = null

// Source: sanity\lib\queries.ts
// Variable: contactPageQuery
// Query: *[_type == "contactPage"][0]{    title,    heroTitle,    heroSubtitle,    contactMethods,    storeLocation,    businessHours,    contactFormSettings,    faqSection,    socialLinks,    seo  }
export type ContactPageQueryResult = null

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == "settings"][0]': SettingsQueryResult
    '*[_type == "storeSettings"][0]{\n  storeName,\n  tagline,\n  logo,\n  heroImage,\n  heroTitle,\n  heroSubtitle,\n  "featuredCategories": featuredCategories[]->{\n    _id,\n    name,\n    "slug": slug.current,\n    description,\n    image\n  },\n  aboutSection,\n  contactInfo,\n  socialMedia,\n  deliveryInfo,\n  announcement\n}': StoreSettingsQueryResult
    '\n  *[_type == "product" && isAvailable == true] | order(isFeatured desc, name asc) {\n    \n  _id,\n  name,\n  "slug": slug.current,\n  description,\n  image,\n  gallery,\n  "category": category->{\n    _id,\n    name,\n    "slug": slug.current\n  },\n  basePrice,\n  servingSize,\n  servesCount,\n  "addOns": addOns[]->{\n    _id,\n    name,\n    "slug": slug.current,\n    description,\n    price,\n    image,\n    isAvailable\n  },\n  "seasonings": seasonings[]->{\n    _id,\n    name,\n    "slug": slug.current,\n    description,\n    price,\n    image,\n    isIncludedByDefault,\n    isAvailable\n  },\n  ingredients,\n  nutritionInfo,\n  isAvailable,\n  isFeatured,\n  preparationTime\n\n  }\n': AllProductsQueryResult
    '\n  *[_type == "product" && isAvailable == true && isFeatured == true] | order(name asc) {\n    \n  _id,\n  name,\n  "slug": slug.current,\n  description,\n  image,\n  gallery,\n  "category": category->{\n    _id,\n    name,\n    "slug": slug.current\n  },\n  basePrice,\n  servingSize,\n  servesCount,\n  "addOns": addOns[]->{\n    _id,\n    name,\n    "slug": slug.current,\n    description,\n    price,\n    image,\n    isAvailable\n  },\n  "seasonings": seasonings[]->{\n    _id,\n    name,\n    "slug": slug.current,\n    description,\n    price,\n    image,\n    isIncludedByDefault,\n    isAvailable\n  },\n  ingredients,\n  nutritionInfo,\n  isAvailable,\n  isFeatured,\n  preparationTime\n\n  }\n': FeaturedProductsQueryResult
    '\n  *[_type == "product" && slug.current == $slug][0] {\n    \n  _id,\n  name,\n  "slug": slug.current,\n  description,\n  image,\n  gallery,\n  "category": category->{\n    _id,\n    name,\n    "slug": slug.current\n  },\n  basePrice,\n  servingSize,\n  servesCount,\n  "addOns": addOns[]->{\n    _id,\n    name,\n    "slug": slug.current,\n    description,\n    price,\n    image,\n    isAvailable\n  },\n  "seasonings": seasonings[]->{\n    _id,\n    name,\n    "slug": slug.current,\n    description,\n    price,\n    image,\n    isIncludedByDefault,\n    isAvailable\n  },\n  ingredients,\n  nutritionInfo,\n  isAvailable,\n  isFeatured,\n  preparationTime\n\n  }\n': ProductBySlugQueryResult
    '\n  *[_type == "product" && isAvailable == true && category->slug.current == $categorySlug] | order(name asc) {\n    \n  _id,\n  name,\n  "slug": slug.current,\n  description,\n  image,\n  gallery,\n  "category": category->{\n    _id,\n    name,\n    "slug": slug.current\n  },\n  basePrice,\n  servingSize,\n  servesCount,\n  "addOns": addOns[]->{\n    _id,\n    name,\n    "slug": slug.current,\n    description,\n    price,\n    image,\n    isAvailable\n  },\n  "seasonings": seasonings[]->{\n    _id,\n    name,\n    "slug": slug.current,\n    description,\n    price,\n    image,\n    isIncludedByDefault,\n    isAvailable\n  },\n  ingredients,\n  nutritionInfo,\n  isAvailable,\n  isFeatured,\n  preparationTime\n\n  }\n': ProductsByCategoryQueryResult
    '\n  *[_type == "productCategory"] | order(order asc, name asc) {\n    _id,\n    name,\n    "slug": slug.current,\n    description,\n    image,\n    "productCount": count(*[_type == "product" && references(^._id) && isAvailable == true])\n  }\n': AllCategoriesQueryResult
    '\n  *[_type == "productCategory" && slug.current == $slug][0] {\n    _id,\n    name,\n    "slug": slug.current,\n    description,\n    image\n  }\n': CategoryBySlugQueryResult
    '\n  *[_type == "productAddOn" && isAvailable == true] | order(name asc) {\n    _id,\n    name,\n    "slug": slug.current,\n    description,\n    price,\n    image\n  }\n': AllAddOnsQueryResult
    '\n  *[_type == "seasoning" && isAvailable == true] | order(name asc) {\n    _id,\n    name,\n    "slug": slug.current,\n    description,\n    price,\n    image,\n    isIncludedByDefault\n  }\n': AllSeasoningsQueryResult
    '\n  *[_type == \'page\' && slug.current == $slug][0]{\n    _id,\n    _type,\n    name,\n    slug,\n    heading,\n    subheading,\n    "pageBuilder": pageBuilder[]{\n      ...,\n      _type == "callToAction" => {\n        ...,\n        button {\n          ...,\n          \n  link {\n      ...,\n      \n  _type == "link" => {\n    "page": page->slug.current,\n    "post": post->slug.current\n  }\n\n      }\n\n        }\n      },\n      _type == "infoSection" => {\n        content[]{\n          ...,\n          markDefs[]{\n            ...,\n            \n  _type == "link" => {\n    "page": page->slug.current,\n    "post": post->slug.current\n  }\n\n          }\n        }\n      },\n    },\n  }\n': GetPageQueryResult
    '\n  *[_type == "page" || _type == "post" && defined(slug.current)] | order(_type asc) {\n    "slug": slug.current,\n    _type,\n    _updatedAt,\n  }\n': SitemapDataResult
    '\n  *[_type == "post" && defined(slug.current)] | order(date desc, _updatedAt desc) {\n    \n  _id,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  "title": coalesce(title, "Untitled"),\n  "slug": slug.current,\n  excerpt,\n  coverImage,\n  "date": coalesce(date, _updatedAt),\n  "author": author->{firstName, lastName, picture},\n\n  }\n': AllPostsQueryResult
    '\n  *[_type == "post" && _id != $skip && defined(slug.current)] | order(date desc, _updatedAt desc) [0...$limit] {\n    \n  _id,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  "title": coalesce(title, "Untitled"),\n  "slug": slug.current,\n  excerpt,\n  coverImage,\n  "date": coalesce(date, _updatedAt),\n  "author": author->{firstName, lastName, picture},\n\n  }\n': MorePostsQueryResult
    '\n  *[_type == "post" && slug.current == $slug] [0] {\n    content[]{\n    ...,\n    markDefs[]{\n      ...,\n      \n  _type == "link" => {\n    "page": page->slug.current,\n    "post": post->slug.current\n  }\n\n    }\n  },\n    \n  _id,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  "title": coalesce(title, "Untitled"),\n  "slug": slug.current,\n  excerpt,\n  coverImage,\n  "date": coalesce(date, _updatedAt),\n  "author": author->{firstName, lastName, picture},\n\n  }\n': PostQueryResult
    '\n  *[_type == "post" && defined(slug.current)]\n  {"slug": slug.current}\n': PostPagesSlugsResult
    '\n  *[_type == "page" && defined(slug.current)]\n  {"slug": slug.current}\n': PagesSlugsResult
    '\n  *[_type == "aboutPage"][0]{\n    title,\n    heroImage,\n    heroTitle,\n    heroSubtitle,\n    mainContent,\n    mission,\n    vision,\n    values,\n    teamSection,\n    ctaSection,\n    seo\n  }\n': AboutPageQueryResult
    '\n  *[_type == "contactPage"][0]{\n    title,\n    heroTitle,\n    heroSubtitle,\n    contactMethods,\n    storeLocation,\n    businessHours,\n    contactFormSettings,\n    faqSection,\n    socialLinks,\n    seo\n  }\n': ContactPageQueryResult
  }
}
